sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov